name: Hello World Workflow
on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: hello world
              run: echo "Hello World"
              shell: bash
    
    goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: GoodByee
              run: echo "GoodByee World"
              shell: bash